// vue-client/src/components/UserSelect.vue
<template>
  <div class="container">
    <label>Please select a user:</label>
    <select v-model="selected" class="form-select">
      <option value="Nemo">Nemo</option>
      <option value="Pierre">Pierre</option>
    </select>
  </div>
</template>

<script>
export default {
  name: "UserSelect",
  data() {
    return {
      selected: "",
    };
  },
  mounted() {
    console.log(this.selected);
  },
  updated() {
    this.$emit("user-selected", this.selected);
  },
};
</script>

<style scoped></style>

// react-client/src/components/UserSelect.jsx
import React from 'react';
class UserSelect extends React.Component {
    render () {
        const users = [
            {name: 'Nemo', key:1}, 
            {name: 'Pierre', key: 2}
        ].map((user) => <option key={user.key} value={user.name}>{user.name}</option>);
        return (
            <div>
                <select>
                    {users}
                </select>       
            </div>
        )
    }
}
export default UserSelect;
