// react-client/src/features/chat/components/UserSelect.jsx
import React, { useState } from 'react';
// import React from 'react';
// import { useSelector, useDispatch } from 'react-redux';
function UserSelect() {
    const [user, setUser] = useState('');
    const changeHandler = function(e) {
        console.log(`${e.target.value} was selected!`);
    }
    const users = [
        {name: 'Nemo', key:1}, 
        {name: 'Pierre', key: 2}
    ].map((user) => <option key={user.key} value={user.name}>{user.name}</option>);
    

    return (
    <div>
        <select onChange={changeHandler}>
            {users}
        </select>       
    </div>
    );
}

export default UserSelect;

// vue-client/src/components/UserSelect.vue
<template>
  <div class="container">
    <label>Please select a user:</label>
    <select v-model="selected" class="form-select">
      <option value="Nemo">Nemo</option>
      <option value="Pierre">Pierre</option>
    </select>
  </div>
</template>

<script>
export default {
  name: "UserSelect",
  data() {
    return {
      selected: "",
    };
  },
  mounted() {
    console.log(this.selected);
  },
  updated() {
    this.$emit("user-selected", this.selected);
  },
};
</script>

<style scoped></style>
