// react-client/src/components/Message.jsx
import React from 'react';

class Message extends React.Component {
    render() {
        const messageData = this.props.messageData;
        return (
            <div className="container">
                <p className="message">
                    {messageData?.message}
                </p>
                <slot></slot>
            </div>
        )
    }
}

export default Message;

// client/src/components/Message.vue
<template>
    <div class="container">
        <p class="message">
            {{ messageData?.message }}
        </p>
    </div>
</template>

<script>
export default {
  name: 'Message',
  props: {
      messageData: Object
  }
}
</script>

<style scoped>
/* .message {
    color: red;
} */
</style>
